version: "3.4"

services:
  prebotsmanager:
    image: canonicalrobots/robotprogrammanager:v1.0
    hostname: prebotsmanager
    container_name: canonicalrobots-robotProgramManager
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80    
    ports:
      - "81:80"    
    volumes:     
      - web_data
    networks:
      - default
    env_file:
      - dev.env

  robotpostprocessorservice:
    image: canonicalrobots/elfin_robotpostprocessorservice:v1.0
    hostname: postProcessorElfin5
    container_name: canonicalrobots-robotPostProcessor-Elfin5
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80      
    ports:
      - "80"     
    volumes:     
      - web_data
    networks:
      - default
    env_file:
       - dev.env

  robotcommunicationservice:
    image: canonicalrobots/elfin_robotcommunicationservice:v1.0
    hostname: communicationServiceElfin5
    container_name: canonicalrobots-robotCommunicationService-Elfin5
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"        
    networks:
      - default
    env_file:
        - dev.env 

volumes:
   web_data:  
